import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PrimeReactProvider, PrimeReactContext } from "primereact/api";
import "./globals.css";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import StoreProvider from "./StoreProvider";
import AuthProvider from "@/helpers/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alumni Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <PrimeReactProvider>
          <StoreProvider>
            <body className={inter.className}>{children}</body>
          </StoreProvider>
        </PrimeReactProvider>
      </AuthProvider>
    </html>
  );
}
