import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import AuthProvider from "@/helpers/provider";

export const metadata: Metadata = {
  title: "Alumni Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <AuthProvider>
          <StoreProvider>{children}</StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
